from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MODEL_PATH = ROOT / "models" / "packet" / "barcodescanner.onnx"
MODEL_INPUT_SIZE = 640
DETECTION_CONFIDENCE = 0.40
NMS_IOU_THRESHOLD = 0.45
ALLOWED_DIGIT_LENGTHS = (7, 8)
BARCODE_REGION_RATIO = (0.0, 0.65)
OCR_REGION_RATIO = (0.35, 1.0)
BLUR_THRESHOLD = 35.0
CONFIRMATION_FRAMES = 3
CAMERA_INDEX = 0
CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
